[package]
name = "gpuitop_properties"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
gpuitop_core = { path = "../core" }
gpuitop_components = { path = "../components" }
procfs = { workspace = true }
users = { workspace = true }
gpui = { workspace = true }
gpui-component = { workspace = true }
bytesize = { workspace = true }
hotpath = { workspace = true }

[features]
default = []
hotpath = ["hotpath/hotpath"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-mcp = ["hotpath/hotpath-mcp"]
