[package]
name = "gpuitop_settings"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Kyza"]
description = "A GPU-accelerated task manager with per-process VRAM tracking"

[dependencies]
gpuitop_core = { path = "../core" }
gpuitop_components = { path = "../components" }
gpui = { workspace = true }
gpui-component = { workspace = true }
open = { workspace = true }
