[package]
name = "gpuitop_processes"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
gpuitop_core = { path = "../core" }
gpuitop_icons = { path = "../icons" }
gpuitop_snapshot = { path = "../snapshot" }
gpuitop_window_picker = { path = "../window_picker" }
gpuitop_components = { path = "../components" }
gpuitop_properties = { path = "../properties" }
gpui = { workspace = true }
gpui-component = { workspace = true }
bytesize = { workspace = true }
libc = { workspace = true }
procfs = { workspace = true }
hotpath = { workspace = true }

[features]
default = []
hotpath = ["hotpath/hotpath"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-mcp = ["hotpath/hotpath-mcp"]
